# travis.yml
sudo: required

language: php

services:
   - docker

script:
  # Build docker image
  - docker login -u "$DOCKER_USERNAME" -p "$DOCKER_PASSWORD"
  - docker build -t $DOCKER_ACC/$DOCKER_REPO:$IMG_TAG .
  - docker push $DOCKER_ACC/$DOCKER_REPO:$IMG_TAG
 #post_install:
 # - docker login -u "$DOCKER_USERNAME" -p "$DOCKER_PASSWORD"
#  - docker push $DOCKER_ACC/$DOCKER_REPO:$IMG_TAG


before_deploy:
   # Install terraform
   - wget https://releases.hashicorp.com/terraform/0.12.7/terraform_0.12.7_linux_amd64.zip
   - unzip terraform_0.12.7_linux_amd64.zip
   - sudo mv terraform /usr/local/bin/
deploy:
   - provider: script
     script: terraform taint $TERRAFORM_INSTANCE && terraform apply -auto-approve
     on:
      branch: master
